In [409]:
import pandas as pd
import numpy as np
import string

In [410]:
## 1a: Parse through data
amazon = pd.read_table('/Users/leighajarett/Downloads/sent/amazon_cells_labelled.txt', sep ='\t', header = None)
yelp = pd.read_table('/Users/leighajarett/Downloads/sent/yelp_labelled.txt', sep ='\t', header = None)

In [35]:
#imdb = pd.read_excel('/Users/leighajarett/Downloads/sent/imdb_labelled1.xlsx', header = None)

In [36]:
#imdb.to_csv('/Users/leighajarett/Desktop/imdb.csv', index = False)

In [411]:
imdb = pd.read_csv('/Users/leighajarett/Desktop/imdb.csv', skiprows = 1, header = None)

In [5]:
# are the labels balanced?
amazon[1].value_counts()

1    500
0    500
Name: 1, dtype: int64

In [6]:
imdb[1].value_counts()

1    500
0    500
Name: 1, dtype: int64

In [7]:
yelp[1].value_counts()

1    500
0    500
Name: 1, dtype: int64

In [412]:
#1b: Preprocessing 

#make lowercase
amazon = amazon.apply(lambda x: x.astype(str).str.lower())
imdb = imdb.apply(lambda x: x.astype(str).str.lower())
yelp = yelp.apply(lambda x: x.astype(str).str.lower())

# ref: http://stackoverflow.com/questions/39512002/convert-whole-dataframe-from-lower-case-to-upper-case-with-pandas

In [413]:
# remove punctuation
def remove_punc(text):
    for punctuation in string.punctuation:
        text = text.replace(punctuation,'')
    return text

In [414]:
strings_a = amazon[0].apply(remove_punc)
labels_a = amazon[1]
amazon = pd.concat([strings_a, labels_a], axis=1)

In [415]:
strings_i = imdb[0].apply(remove_punc)
labels_i = imdb[1]
imdb = pd.concat([strings_i, labels_i], axis=1)

In [416]:
strings_y = yelp[0].apply(remove_punc)
labels_y = yelp[1]
yelp = pd.concat([strings_y, labels_y], axis=1)

In [13]:
#ref: http://stackoverflow.com/questions/18062135/combining-two-series-into-a-dataframe-in-pandas
#ref: http://chrisalbon.com/python/pandas_apply_operations_to_dataframes.html

In [14]:
import nltk

from nltk.corpus import stopwords
stop = stopwords.words('english')

In [15]:
# tokenize and get rid of stop words

In [16]:
amazon[0] = amazon.apply(lambda row: nltk.word_tokenize(row[0]), axis=1)
amazon[0]=amazon[0].apply(lambda x: [item for item in x if item not in stop])

In [17]:
imdb[0] = imdb.apply(lambda row: nltk.word_tokenize(row[0]), axis=1)
imdb[0]=imdb[0].apply(lambda x: [item for item in x if item not in stop])

In [18]:
yelp[0] = yelp.apply(lambda row: nltk.word_tokenize(row[0]), axis=1)
yelp[0]=yelp[0].apply(lambda x: [item for item in x if item not in stop])

In [19]:
# lemmatize
from nltk.stem.wordnet import WordNetLemmatizer
lmt = WordNetLemmatizer()

In [20]:
amazon[0] = amazon[0].apply(lambda x: [lmt.lemmatize(y) for y in x])
yelp[0] = yelp[0].apply(lambda x: [lmt.lemmatize(y) for y in x])
imdb[0] = imdb[0].apply(lambda x: [lmt.lemmatize(y) for y in x])

In [21]:
## 1c: Splitting trainting and testing data
training = pd.concat([amazon[0:800], imdb[0:800], yelp[0:800]], axis=0)
testing = pd.concat([amazon[800:1000], imdb[800:1000], yelp[800:1000]], axis=0)

training = training.reset_index(drop=True)
testing = testing.reset_index(drop=True)

In [22]:
# ## 1d: Bag of Words
# #list1 = training[0]

# asd = []
# for i in range(0, len(list1)):
#    a = dict((el,1) for el in list1[i])
#    asd.append(a)

# X_train = pd.DataFrame(asd)
# X_train = X_train.fillna(0)

In [23]:
## 1d: Bag of Words

list_tr1 = list(training[0])
len(list_tr1) 

2400

In [24]:
list_tr2 = [val for sublist in list_tr1 for val in sublist]
unique_tr = set(list_tr2)
len(unique_tr)

4220

In [25]:
list_ts1 = list(testing[0])
len(list_ts1)

600

In [26]:
list_ts2 = [val for sublist in list_ts1 for val in sublist]
unique_ts = set(list_ts2)
len(unique_ts)

1766

In [27]:
u = unique_tr - unique_ts
len(u)

3098

In [28]:
v = unique_ts - unique_tr
len(v)

644

In [29]:
list_all = list_tr1 + list_ts1
len(list_all)

3000

In [30]:
list_all2 = [val for sublist in list_all for val in sublist]
unique_all = set(list_all2)
len(unique_all)

4864

In [31]:
from collections import Counter

In [32]:
asd = []
for i in range(0, len(list_all)):
    a = dict(Counter(list_all[i]))
    asd.append(a)

In [33]:
X = pd.DataFrame(asd)
X = X.fillna(0)
X.shape

(3000, 4864)

In [34]:
X.drop(v,inplace=True,axis=1)
X.shape

(3000, 4220)

In [35]:
# Where are the numbers?
x = list(X.columns.values)[0:70]  

In [36]:
# get rid of all the numbers - delete columns 0:70

X_new = X[X.columns[70:4216]]

In [38]:
X_new[0:2]

aailiyah  abandoned  abhor  ability  able  abound  abroad  absolute  \
0       0.0        0.0    0.0      0.0   0.0     0.0     0.0       0.0   
1       0.0        0.0    0.0      0.0   0.0     0.0     0.0       0.0   

   absolutel  absolutely  ...   youre  youthful  youtube  yucky  yukon  yum  \
0        0.0         0.0  ...     0.0       0.0      0.0    0.0    0.0  0.0   
1        0.0         0.0  ...     0.0       0.0      0.0    0.0    0.0  0.0   

   yummy  yun    z  zero  
0    0.0  0.0  0.0   0.0  
1    0.0  0.0  0.0   0.0  

[2 rows x 4146 columns]

In [39]:
X_train = X_new[0:2400]

In [40]:
X_test = X_new[2400:3000]
X_test = X_test.reset_index(drop=True)

In [721]:
# 1e: Standardize 
norm = (X_train.ix[0] - X_train.ix[0].mean(axis=0))/ X_train.ix[0].var(axis=0)
for i in np.arange(1,2400):
    x= (X_train.ix[i] - X_train.ix[i].mean(axis=0))/ X_train.ix[i].var(axis=0)
    norm = pd.concat((norm, x), axis=1)

In [724]:
#testing
normt = (X_test.ix[0] - X_test.ix[0].mean(axis=0))/ X_test.ix[0].var(axis=0)
for i in np.arange(1,600):
    x= (X_test.ix[i] - X_test.ix[i].mean(axis=0))/ X_test.ix[i].var(axis=0)
    normt = pd.concat((normt, x), axis=1)

In [725]:
X_train_norm = norm.T

In [726]:
X_test_norm = normt.T

In [45]:
### 1f: K-means

In [191]:
from sklearn.metrics.pairwise import euclidean_distances

In [729]:
X_train_norm = X_train_norm.fillna(value = 0)

In [730]:
X_test_norm = X_test_norm.fillna(value = 0)

In [742]:
data = X_train_norm

o = np.random.choice(range(data.shape[0]),2,replace=False)
centers = data.ix[o,:]
c1 = centers.ix[[o[0]]]
c2 = centers.ix[[o[1]]]

iteration = 0
#repeat n times
while iteration < 10: 
    iteration=iteration+1

    #inialize variables 
    group1 = []
    group2 = []
    d1 = []
    d2 = []
    #get a list of distances -> d1 is a list of corresponding distances to c1
    #d2 is a list of corresponding distances to c2
    for i in range(data.shape[0]):
        x1 = euclidean_distances(c1,data.ix[i,:].reshape(1,-1))
        d1 = d1 + [x1[0][0]] 
        x2 = euclidean_distances(c2,data.ix[i,:].reshape(1,-1))
        d2 = d2 + [x2[0][0]] 

    d = [d1,d2]
    mins = np.argmin(d, axis = 0) #find the index of the smaller distance for each column -- if 0 then closer to c1
    for j in range(data.shape[0]):
        if mins[j] == 0:  #if the value in d1 was smaller for i, let i be in group1
            group1.append(j)
        if mins[j] == 1:  #if the value in d2 was smaller for i, let i be in group2
            group2.append(j)

    #update the centers with the average of the group 
    g1 = data.ix[group1,:]
    g1_mean = g1.mean(axis=0)
    c1 = pd.DataFrame(g1_mean.reshape(1,-1))
    g2 = data.ix[group2,:]
    g2_mean = g2.mean(axis=0)
    c2 = pd.DataFrame(g2_mean.reshape(1,-1))


In [752]:
o

array([ 285, 1282])

In [756]:
#find what the reviews are 
amazon = pd.read_table('/Users/leighajarett/Downloads/sent/amazon_cells_labelled.txt', sep ='\t', header = None)
amazon.ix[285,:]


0    Great phone!.
1                1
Name: 285, dtype: object

In [759]:
imdb = pd.read_csv('/Users/leighajarett/Desktop/imdb.csv', skiprows = 1, header = None)
imdb.ix[282,:]

0    Here's where the movie really pi**ed me off.  
1                                                 0
Name: 282, dtype: object

In [743]:
#getting labels for group1
train_labs = training.ix[group1,1]
train_labs.value_counts()

1    101
0      2
Name: 1, dtype: int64

In [744]:
#getting labels for group2
train_labs2 = training.ix[group2,1]
train_labs2.value_counts()

0    1151
1    1146
Name: 1, dtype: int64

In [391]:
from sklearn.cluster import KMeans

In [760]:
#test using sklearn kmeans
kmeans = KMeans(n_clusters=2, random_state=0).fit_predict(X_train_norm)

In [761]:
np.bincount(kmeans)

array([ 115, 2285])

In [309]:
Y_train = training.ix[:,1] #training labels
Y_test = testing.ix[:,1] #testing labels

In [304]:
# 1g: Logistic regression model
from sklearn import linear_model

In [766]:
cls = linear_model.LogisticRegression()
fit = cls.fit(X_train_norm, Y_train)

In [767]:
predic_labels = fit.predict(X_test_norm)

In [764]:
def accuracy(predic_label,actual_label): 
    good = 0
    for i in range(0,len(predic_label)):
        if predic_label[i] == actual_label[i]:
            good =good+1  #if labels match then good gets a 1, if not good gets a 0
        else:
            good =good+0
    return(good/len(predic_label))

In [768]:
acc = accuracy(predic_labels, Y_test)
acc 

0.7066666666666667

In [769]:
# confusion matrix 
from sklearn.metrics import confusion_matrix
confusion_matrix(Y_test, predic_labels)

array([[255,  92],
       [ 84, 169]])

In [505]:
# Inspect weight vector
w = fit.coef_
idx = (-w).argsort()[:10]
idx[0][0:10]

array([1569, 2114, 2390,  912, 1223, 1301,  110,  233, 2115, 2059])

In [510]:
nams = list(data_fill.columns.values)
print(nams[1569], nams[2114], nams[2390], nams[912], nams[1223], nams[1301], nams[110], nams[233], nams[2115], nams[2059])

great love nice delicious excellent fantastic amazing awesome loved liked


In [ ]:
# Ngram model, n=2

In [456]:
#start with original data
#take out punctuation and make all lowercase

amazon = pd.read_table('/Users/leighajarett/Downloads/sent/amazon_cells_labelled.txt', sep ='\t', header = None)
yelp = pd.read_table('/Users/leighajarett/Downloads/sent/yelp_labelled.txt', sep ='\t', header = None)
imdb = pd.read_csv('/Users/leighajarett/Desktop/imdb.csv', skiprows = 1, header = None)

amazon = amazon.apply(lambda x: x.astype(str).str.lower())
imdb = imdb.apply(lambda x: x.astype(str).str.lower())
yelp = yelp.apply(lambda x: x.astype(str).str.lower())

strings_a = amazon[0].apply(remove_punc)
labels_a = amazon[1]
amazon = pd.concat([strings_a, labels_a], axis=1)

strings_i = imdb[0].apply(remove_punc)
labels_i = imdb[1]
imdb = pd.concat([strings_i, labels_i], axis=1)

strings_y = yelp[0].apply(remove_punc)
labels_y = yelp[1]
yelp = pd.concat([strings_y, labels_y], axis=1)


In [473]:
# separate into training and testing
training_n = pd.concat([amazon[0:800], imdb[0:800], yelp[0:800]], axis=0)
testing_n = pd.concat([amazon[800:1000], imdb[800:1000], yelp[800:1000]], axis=0)

training_n = training_n.reset_index(drop=True)
testing_n = testing_n.reset_index(drop=True)

In [419]:
#get ngrams for a string
def ngrams(input, n):
    input = input.split(' ')
    output = []
    for i in range(len(input)-n+1):
        output.append(input[i:i+n])
    return output
#http://stackoverflow.com/questions/13423919/computing-n-grams-using-python

In [474]:
#make dictionary of ngrams for training 
dict_n= []
for i in range(2400):
    n = ngrams(training_n[0][i],2)
    dict_n = dict_n + n  

In [527]:
unique_ngrams = [list(x) for x in set(tuple(x) for x in dict_n)]
#http://stackoverflow.com/questions/3724551/python-uniqueness-for-list-of-lists

In [533]:
#get ngrams for all data
amazon[0] = amazon[0].apply(lambda x: ngrams(x,2))
imdb[0] = imdb[0].apply(lambda x: ngrams(x,2))
yelp[0] = yelp[0].apply(lambda x: ngrams(x,2))

In [542]:
#separate the ngrams into testing and training
training_ngram = pd.concat([amazon[0:800], imdb[0:800], yelp[0:800]], axis=0)
testing_ngram = pd.concat([amazon[800:1000], imdb[800:1000], yelp[800:1000]], axis=0)

training_ngram = training_ngram.reset_index(drop=True)
testing_ngram = testing_ngram.reset_index(drop=True)


In [532]:
#make bag of ngrams
ntrain_bagwords = np.zeros((2400,len(unique_ngrams)))

In [566]:
for i in range(len(unique_ngrams)):
    for j in range(2400):
        if unique_ngrams[i] in training_ngram[0][j]:
            ntrain_bagwords[j][i] = 1

In [579]:
df = pd.DataFrame(ntrain_bagwords)

In [583]:
df_names = unique_ngrams

In [585]:
#make bag of words for testing
ntest_bagwords = np.zeros((600,len(unique_ngrams)))

for i in range(len(unique_ngrams)):
    for j in range(600):
        if unique_ngrams[i] in testing_ngram[0][j]:
            ntest_bagwords[j][i] = 1

In [586]:
df_test = pd.DataFrame(ntest_bagwords)

In [771]:
#Standardize the testing and training
Xng_train_norm = (df.ix[0] - df.ix[0].mean(axis=0))/ df.ix[0].var(axis=0)
for i in np.arange(1,2400):
    x= (df.ix[i] - df.ix[i].mean(axis=0))/ df.ix[i].var(axis=0)
    Xng_train_norm = pd.concat((Xng_train_norm, x), axis=1)
    
Xng_test_norm = (df_test.ix[0] - df_test.ix[0].mean(axis=0))/ df_test.ix[0].var(axis=0)
for i in np.arange(1,600):
    x= (df_test.ix[i] - df_test.ix[i].mean(axis=0))/ df_test.ix[i].var(axis=0)
    Xng_test_norm = pd.concat((Xng_test_norm, x), axis=1)


In [772]:
Xng_test_norm = norm_ntest.T
Xng_train_norm = norm_ntr.T

Xng_test_norm = Xng_test_norm.fillna(value = 0)
Xng_train_norm = Xng_train_norm.fillna(value = 0)

In [773]:
#K-means cluster on ngrams training bag of words

data = Xng_train_norm

o = np.random.choice(range(data.shape[0]),2,replace=False)
centers = data.ix[o,:]
c1 = centers.ix[[o[0]]]
c2 = centers.ix[[o[1]]]

iteration = 0
#repeat n times
while iteration < 10: 
    iteration=iteration+1

    #inialize variables 
    group1 = []
    group2 = []
    d1 = []
    d2 = []
    #get a list of distances -> d1 is a list of corresponding distances to c1
    #d2 is a list of corresponding distances to c2
    for i in range(data.shape[0]):
        x1 = euclidean_distances(c1,data.ix[i,:].reshape(1,-1))
        d1 = d1 + [x1[0][0]] 
        x2 = euclidean_distances(c2,data.ix[i,:].reshape(1,-1))
        d2 = d2 + [x2[0][0]] 

    d = [d1,d2]
    mins = np.argmin(d, axis = 0) #find the index of the smaller distance for each column -- if 0 then closer to c1
    for j in range(data.shape[0]):
        if mins[j] == 0:  #if the value in d1 was smaller for i, let i be in group1
            group1.append(j)
        if mins[j] == 1:  #if the value in d2 was smaller for i, let i be in group2
            group2.append(j)

    #update the centers with the average of the group 
    g1 = data.ix[group1,:]
    g1_mean = g1.mean(axis=0)
    c1 = pd.DataFrame(g1_mean.reshape(1,-1))
    g2 = data.ix[group2,:]
    g2_mean = g2.mean(axis=0)
    c2 = pd.DataFrame(g2_mean.reshape(1,-1))


In [774]:
#Check out results of KMeans

#getting labels for group1
train_labs_n1 = training.ix[group1,1]
train_labs_n1.value_counts()

1    1071
0     938
Name: 1, dtype: int64

In [775]:
#getting labels for group2
train_labs_n2 = training.ix[group2,1]
train_labs_n2.value_counts()

0    215
1    176
Name: 1, dtype: int64

In [780]:
# get centers
o

array([1724,  868])

In [790]:
training_n.ix[868,:][0]

'this movie totally grates on my nerves  '

In [789]:
training_n.ix[1724,:][0]

'we thought youd have to venture further away to get good sushi but this place really hit the spot that night'

In [776]:
#Repeat Logistic Regression
cls = linear_model.LogisticRegression()
fit = cls.fit(Xng_train_norm, Y_train) 

In [777]:
predic_labels_n = fit.predict(Xng_test_norm)

In [778]:
#get accruacy
acc_n = accuracy(predic_labels_n, Y_test)
acc_n

0.6966666666666667

In [779]:
#get confusion matrix 
confusion_matrix(Y_test, predic_labels_n)

array([[235, 112],
       [ 70, 183]])

In [599]:
#inspect weight vector 
w = fit.coef_
idx = (-w).argsort()[:5]
idx[0][0:10]

array([ 5209, 10483, 14285, 14164,  4024, 13669,  9128,  9973,  2173, 10109])

In [600]:
print(unique_ngrams[5209], unique_ngrams[10483], unique_ngrams[14285], unique_ngrams[14164], unique_ngrams[4024], unique_ngrams[13669], unique_ngrams[9128], unique_ngrams[9973], unique_ngrams[2173], unique_ngrams[10109])

['works', 'great'] ['a', 'great'] ['the', 'best'] ['very', 'good'] ['love', 'this'] ['great', 'phone'] ['is', 'good'] ['love', 'the'] ['well', ''] ['i', 'liked']


In [638]:
# PCA 
#http://sebastianraschka.com/Articles/2014_pca_step_by_step.html

#working with normalized feature vectors X_test_fill, Y_test, X_train_norm, Y_train
#combine testing and training to perform PCA on all data
all_data = pd.concat((data_fill,X_test_fill))
all_data_labels = pd.concat((Y_train,Y_test))
               

In [602]:
#compute mean training feature vector 
#train_mean = X_train_norm.mean(axis=0)

In [639]:
#computing covariance matrix
cov_mat = np.cov(all_data.T)
cov_mat.shape


(4146, 4146)

In [640]:
# Compute eigenvectors and corresponding eigenvalues
eig_val, eig_vec = np.linalg.eig(cov_mat)


In [641]:
# Sorting eigenvectors by decreasing eigenvalues

#pair eigenvectors and values
eig_pairs = [(np.abs(eig_val[i]), eig_vec[:,i]) for i in range(len(eig_val))]

#sort
eig_pairs.sort(key=lambda x: x[0], reverse=True)

In [642]:
eig_pairs[0]

(104797.32244680138,
 array([  1.97396706e-04+0.j,   2.92788586e-05+0.j,  -2.85953675e-04+0.j,
        ...,   2.92788586e-05+0.j,   6.73659117e-05+0.j,
          6.20491522e-04+0.j]))

In [643]:
#Reduce to 10-d
#make a matrix of eigenvalues along the columns, so will have 10 columns 
matrix_w_10 = eig_pairs[0][1].reshape(4146,1)
for i in np.arange(1,10):
    matrix_w_10 = np.hstack((matrix_w_10,eig_pairs[i][1].reshape(4146,1)))

In [644]:
matrix_w_10.shape

(4146, 10)

In [649]:
#transform samples onto new subspace
transformed_10 = matrix_w_10.T.dot(all_data.T)

In [650]:
transformed_10.shape

(10, 3000)

In [665]:
trans_10_data = np.real(transformed_10.T)

In [664]:
#Reduce to 50-d
matrix_w_50 = eig_pairs[0][1].reshape(4146,1)
for i in np.arange(1,50):
    matrix_w_50 = np.hstack((matrix_w_50,eig_pairs[i][1].reshape(4146,1)))
    
transformed_50 = matrix_w_50.T.dot(all_data.T)
trans_50_data = np.real(transformed_50.T)


In [663]:
#Reduce to 100-d
matrix_w_100 = eig_pairs[0][1].reshape(4146,1)
for i in np.arange(1,100):
    matrix_w_100 = np.hstack((matrix_w_100,eig_pairs[i][1].reshape(4146,1)))
    
transformed_100 = matrix_w_100.T.dot(all_data.T)
trans_100_data = np.real(transformed_100.T)


In [674]:
#Repeat Kmeans for 10D

data = pd.DataFrame(trans_10_data[0:2400]) #perform only on training 

o = np.random.choice(range(data.shape[0]),2,replace=False)
centers = data.ix[o,:]
c1 = centers.ix[[o[0]]]
c2 = centers.ix[[o[1]]]

iteration = 0
#repeat n times
while iteration < 10: 
    iteration=iteration+1

    #inialize variables 
    group1 = []
    group2 = []
    d1 = []
    d2 = []
    #get a list of distances -> d1 is a list of corresponding distances to c1
    #d2 is a list of corresponding distances to c2
    for i in range(data.shape[0]):
        x1 = euclidean_distances(c1,data.ix[i,:].reshape(1,-1))
        d1 = d1 + [x1[0][0]] 
        x2 = euclidean_distances(c2,data.ix[i,:].reshape(1,-1))
        d2 = d2 + [x2[0][0]] 

    d = [d1,d2]
    mins = np.argmin(d, axis = 0) #find the index of the smaller distance for each column -- if 0 then closer to c1
    for j in range(data.shape[0]):
        if mins[j] == 0:  #if the value in d1 was smaller for i, let i be in group1
            group1.append(j)
        if mins[j] == 1:  #if the value in d2 was smaller for i, let i be in group2
            group2.append(j)

    #update the centers with the average of the group 
    g1 = data.ix[group1,:]
    g1_mean = g1.mean(axis=0)
    c1 = pd.DataFrame(g1_mean.reshape(1,-1))
    g2 = data.ix[group2,:]
    g2_mean = g2.mean(axis=0)
    c2 = pd.DataFrame(g2_mean.reshape(1,-1))


In [675]:
#look at results
#getting labels for group1
train_labs_pca_10 = training.ix[group1,1]
train_labs_pca_10.value_counts()

1    93
0    21
Name: 1, dtype: int64

In [676]:
#getting labels for group2
train_labs_pca_10 = training.ix[group2,1]
train_labs_pca_10.value_counts()

1    1154
0    1132
Name: 1, dtype: int64

In [677]:
#Repeat Logistic Regresstion for 10D
cls = linear_model.LogisticRegression()
fit = cls.fit(data, Y_train)

In [678]:
predic_labels_pca_10 = fit.predict(pd.DataFrame(trans_10_data[2400:3000]))

In [679]:
acc_pca_10 = accuracy(predic_labels_pca_10, Y_test)
acc_pca_10

0.585

In [680]:
confusion_matrix(Y_test, predic_labels_pca_10)

array([[257,  90],
       [159,  94]])

In [684]:
#Repeat Kmeans for 50D

data = pd.DataFrame(trans_50_data[0:2400]) #perform only on training 

o = np.random.choice(range(data.shape[0]),2,replace=False)
centers = data.ix[o,:]
c1 = centers.ix[[o[0]]]
c2 = centers.ix[[o[1]]]

iteration = 0
#repeat n times
while iteration < 10: 
    iteration=iteration+1

    #inialize variables 
    group1 = []
    group2 = []
    d1 = []
    d2 = []
    #get a list of distances -> d1 is a list of corresponding distances to c1
    #d2 is a list of corresponding distances to c2
    for i in range(data.shape[0]):
        x1 = euclidean_distances(c1,data.ix[i,:].reshape(1,-1))
        d1 = d1 + [x1[0][0]] 
        x2 = euclidean_distances(c2,data.ix[i,:].reshape(1,-1))
        d2 = d2 + [x2[0][0]] 

    d = [d1,d2]
    mins = np.argmin(d, axis = 0) #find the index of the smaller distance for each column -- if 0 then closer to c1
    for j in range(data.shape[0]):
        if mins[j] == 0:  #if the value in d1 was smaller for i, let i be in group1
            group1.append(j)
        if mins[j] == 1:  #if the value in d2 was smaller for i, let i be in group2
            group2.append(j)

    #update the centers with the average of the group 
    g1 = data.ix[group1,:]
    g1_mean = g1.mean(axis=0)
    c1 = pd.DataFrame(g1_mean.reshape(1,-1))
    g2 = data.ix[group2,:]
    g2_mean = g2.mean(axis=0)
    c2 = pd.DataFrame(g2_mean.reshape(1,-1))


In [685]:
#look at results
#getting labels for group1
train_labs_pca_50 = training.ix[group1,1]
train_labs_pca_50.value_counts()

0    102
1     71
Name: 1, dtype: int64

In [686]:
#getting labels for group2
train_labs_pca_50 = training.ix[group2,1]
train_labs_pca_50.value_counts()

1    1176
0    1051
Name: 1, dtype: int64

In [687]:
#Repeat Logistic Regresstion for 50D
cls = linear_model.LogisticRegression()
fit = cls.fit(data, Y_train) 

In [689]:
predic_labels_pca_50 = fit.predict(pd.DataFrame(trans_50_data[2400:3000]))

In [690]:
acc_pca_50 = accuracy(predic_labels_pca_50, Y_test)
acc_pca_50

0.6616666666666666

In [691]:
confusion_matrix(Y_test, predic_labels_pca_50)

array([[252,  95],
       [108, 145]])

In [692]:
#Repeat Kmeans for 100D

data = pd.DataFrame(trans_100_data[0:2400]) #perform only on training 

o = np.random.choice(range(data.shape[0]),2,replace=False)
centers = data.ix[o,:]
c1 = centers.ix[[o[0]]]
c2 = centers.ix[[o[1]]]

iteration = 0
#repeat n times
while iteration < 10: 
    iteration=iteration+1

    #inialize variables 
    group1 = []
    group2 = []
    d1 = []
    d2 = []
    #get a list of distances -> d1 is a list of corresponding distances to c1
    #d2 is a list of corresponding distances to c2
    for i in range(data.shape[0]):
        x1 = euclidean_distances(c1,data.ix[i,:].reshape(1,-1))
        d1 = d1 + [x1[0][0]] 
        x2 = euclidean_distances(c2,data.ix[i,:].reshape(1,-1))
        d2 = d2 + [x2[0][0]] 

    d = [d1,d2]
    mins = np.argmin(d, axis = 0) #find the index of the smaller distance for each column -- if 0 then closer to c1
    for j in range(data.shape[0]):
        if mins[j] == 0:  #if the value in d1 was smaller for i, let i be in group1
            group1.append(j)
        if mins[j] == 1:  #if the value in d2 was smaller for i, let i be in group2
            group2.append(j)

    #update the centers with the average of the group 
    g1 = data.ix[group1,:]
    g1_mean = g1.mean(axis=0)
    c1 = pd.DataFrame(g1_mean.reshape(1,-1))
    g2 = data.ix[group2,:]
    g2_mean = g2.mean(axis=0)
    c2 = pd.DataFrame(g2_mean.reshape(1,-1))


In [693]:
#look at results
#getting labels for group1
train_labs_pca_100 = training.ix[group1,1]
train_labs_pca_100.value_counts()

0    15
1    12
Name: 1, dtype: int64

In [694]:
#getting labels for group2
train_labs_pca_100 = training.ix[group2,1]
train_labs_pca_100.value_counts()

1    1235
0    1138
Name: 1, dtype: int64

In [695]:
#Repeat Logistic Regresstion for 100D
cls = linear_model.LogisticRegression()
fit = cls.fit(data, Y_train) 

In [696]:
predic_labels_pca_100 = fit.predict(pd.DataFrame(trans_100_data[2400:3000]))

In [697]:
acc_pca_100 = accuracy(predic_labels_pca_100, Y_test)
acc_pca_100

0.7133333333333334

In [698]:
confusion_matrix(Y_test, predic_labels_pca_100)

array([[263,  84],
       [ 88, 165]])